### ISSUE TITLE
Issue convert toImage

### ISSUE THREAD

**Issue by GustavoMucino** [wiringbits/fingerprint-reader-daemon#2]
Hi! Thanks for share this project, I follow the steps and everything was ok, my device its a NitGen and I have been able to capture the fingerprint but it doesn´t returns the base64-enconded image, I debugged the code and realized that the error comes from this line : 

"final Image imageFinger = subject.getFingers().get(0).getImage().toImage();" 

Specifically in the toImage() method, it throws the next error : "java.lang.NoSuchMethodError: com.sun.jna.Native.getDirectByteBuffer(JJ)Ljava/nio/ByteBuffer;"

I dont know what could be happen, any idea?

![Screenshot_3](https://user-images.githubusercontent.com/14807362/87104176-b92f9e80-c21c-11ea-80da-7b26be970ffb.png)

Thank you!

**Comment by AlexITC** [comment]
It is very likely you are using a newer Java version where such class was removed, I suggest to try using JDK 8.

**Comment by GustavoMucino** [comment]
Yes I tought that it was the problem because I was using Java 10, but now I tried with the JDK 8 and the error is still there, any other suggestion? Thanks

**Comment by AlexITC** [comment]
Please try running the zip file on #1 , if that fixes the problem it would mean the project has a missing dependency that's required on runtime.

**Comment by GustavoMucino** [comment]
Perfect! It worked with the zip file! Thanks

**Comment by AlexITC** [comment]
Thanks for verifying, I will try to look on fixing the main instructions, sadly I need to renew my trial license to test.
